version: '2'

services:
    redis:
        image: redis:latest

    mongo:
        image: mongo:3.4-jessie
        volumes:
        - mongo_data:/data/db
        command: "--smallfiles"

    web:
        image: thumbsniper/web:latest
        volumes:
        - web_thumbnails:/opt/thumbsniper/web_images/thumbnails
#        - /data/docker/thumbsniper/config/backend-config.inc.php:/opt/thumbsniper/config/backend-config.inc.php
#        - /data/docker/thumbsniper/config/panel-config.inc.php:/opt/thumbsniper/config/panel-config.inc.php


        links:
        - mongo
        - redis
        ports:
        - "80:80"
        networks:
            default:
                aliases:
                    - api.example.com
                    - img.example.com

volumes:
    mongo_data:
    web_thumbnails:
